//! Cross-check the engine-derived [`VariantRules`] model against Fairy-Stockfish's
//! **own declared variant config** (issue #557).
//!
//! The perft oracle only exercises *reachable* positions, so it can never catch a
//! rule that mcr and FSF describe differently but that happens not to affect the
//! node counts of the sampled openings (an outcome-adjudication rule, a promotion
//! set that never gets exercised at shallow depth, …). This test closes that gap by
//! comparing the two *declarations* directly.
//!
//! # How the FSF side is sourced
//!
//! FSF declares each variant as a C++ constructor in
//! `compare-fairy/build/Fairy-Stockfish/src/variant.cpp` (e.g. `chess_variant()`,
//! `shogi_variant()`), building on a default [`Variant`] whose relevant defaults are
//! (`src/variant.h`): `maxRank = RANK_8`, `maxFile = FILE_H` (an 8x8 board),
//! `castling = true`, `doubleStep = true`, `enPassantRegion = AllSquares`,
//! `promotionPieceTypes = {QUEEN, ROOK, BISHOP, KNIGHT}`, `stalemateValue = DRAW`,
//! `extinctionValue = NONE`, `checkCounting = false`, `mustCapture = false`. FSF does
//! not cleanly expose this config over UCI, so rather than parse C++ at runtime the
//! expected values below are **transcribed** from `variant.cpp` (each row cites its
//! constructor), compiled into this test, and asserted against
//! [`VariantRef::rules`]. The table therefore runs in ordinary CI without the FSF
//! binary.
//!
//! # Field mapping (FSF term -> mcr `VariantRules` field)
//!
//! * `maxFile`/`maxRank`            -> `board.{width,height}` (`file/rank + 1`)
//! * `castling`                     -> `castling.enabled`
//! * `promotionPieceTypes`          -> `promotion.roles` (as a set)
//! * `doubleStep`/`doubleStepRegion`-> `pawns.double_step_ranks`
//! * `enPassantRegion`              -> `pawns.en_passant`
//! * `extinction{Value,PieceTypes}` -> `terminal.extinction` / bare-king rules
//! * `flagPiece`/`flagRegion`       -> `terminal.flag_win`
//! * `checkCounting`                -> `terminal.wins_on_check` / `check_count_to_win`
//! * `stalemateValue`               -> `terminal.stalemate_is_loss`
//! * `extinctionPseudoRoyal`/`dupleCheck`/non-royal king -> `terminal.royal`
//!
//! FSF piece types are transcribed to their mcr [`WideRole`] name (FSF `CHANCELLOR`
//! = rook+knight = mcr `Elephant`; FSF `ARCHBISHOP` = bishop+knight = mcr `Hawk`;
//! FSF `AMAZON` = mcr `Angel`; FSF `CENTAUR` = mcr `Kheshig`; FSF `FERS`/`MET` = mcr
//! `Met`; FSF `KHON` = mcr `Silver`; FSF `BERS` = mcr `General`; FSF `ROOKNI`/`KNIROO`
//! = mcr `Rookni`/`Lancer`; FSF `FERS_ALFIL` = mcr `FersAlfil`).
//!
//! Only well-defined mappings are asserted. Genuinely ambiguous fields are skipped
//! and noted:
//!
//! * FSF variants declared in `variants.ini` rather than `variant.cpp` (Orda,
//!   Synochess, Shinobi, Empire, Shogun, Chak, Chennis, Khans, Mansindam, Xiangfu,
//!   Cannon Shogi, Grandhouse, Fog of War) carry no `variant.cpp` config to
//!   transcribe, so they are not covered here. Neither are the non-FSF oracles
//!   (HaChu: Chu/Dai; Independent: Alice/Jieqi/Tenjiku/Wa Shogi).
//! * `promotion.roles` is skipped where FSF's set is per-colour asymmetric (Chigorin,
//!   Spartan) — mcr flattens it to a union — or maps `COMMONER` inconsistently
//!   (Knightmate's Commoner vs Antichess's King), or the variant flips pieces rather
//!   than promoting pawns (Kyoto/Micro/Sho shogi, Dobutsu, Tori).
//!
//! # The divergences this found
//!
//! Two are asserted as **known divergences** in [`known_divergences`] (mcr's current
//! value is pinned so the suite stays green and a future fix trips the test):
//!
//! 1. **`stalemate_is_loss` for the shogi / xiangqi families.** FSF sets
//!    `stalemateValue = -VALUE_MATE` for every shogi variant (`minishogi_variant_base`)
//!    and every xiangqi variant (`minixiangqi_variant`), so a stalemated side *loses*.
//!    mcr leaves the default (`stalemate_is_loss() == false`, i.e. a draw) for all of
//!    them. For xiangqi this is a genuine outcome bug (stalemate is a loss in real
//!    xiangqi); for shogi stalemate is practically unreachable but the declared
//!    adjudication still differs. The perft oracle cannot see it because a stalemated
//!    node already generates zero moves. (Janggi is excluded: it allows passing, so it
//!    cannot be stalemated.)
//! 2. **`double_step_ranks` for Legan.** FSF `legan_variant()` sets
//!    `doubleStep = false`, but mcr reports `[1]`. The Legan pawn's movement is
//!    generated by a dedicated directional path that never performs the standard
//!    double-push (perft matches FSF node-for-node), so the value is a vestigial
//!    artifact of the generic `pawn_may_double_push_from` default — the same reason
//!    the shogi steppers report `[1]` despite being one-step pawns.

use mcr::geometry::{RoyalRule, WideRole};
use mcr::VariantRef;

use WideRole::{
    Angel, Bishop, BishopKnight, Cannon, Elephant, FersAlfil, General, Gold, Grasshopper, Hawk,
    Kheshig, King, KnightBishop, Lancer, Met, Nightrider, Queen, Rook, Rookni, Silver,
};
use WideRole::{Knight as N, Pawn};

/// One transcribed FSF expectation. `None` fields are intentionally not cross-checked
/// (see the module-level notes on skipped mappings).
struct Expect {
    /// mcr name accepted by [`VariantRef::from_name`].
    name: &'static str,
    /// The `variant.cpp` constructor this row is transcribed from.
    cite: &'static str,
    /// `(width, height)` = `(maxFile + 1, maxRank + 1)`. Always checked.
    board: (u8, u8),
    /// FSF `castling`. Always checked.
    castling: bool,
    /// FSF `promotionPieceTypes`, as an mcr role set (order-insensitive).
    promo: Option<&'static [WideRole]>,
    /// White's 0-based double-step ranks from `doubleStep`/`doubleStepRegion`.
    double_step: Option<&'static [u8]>,
    /// Whether `enPassantRegion` leaves en passant available.
    en_passant: Option<bool>,
    /// `stalemateValue == -VALUE_MATE`.
    stalemate_loss: Option<bool>,
    /// FSF `extinction*` describing a bare-king **loss** (`ALL_PIECES`, count 1, `-MATE`).
    bare_king_loss: Option<bool>,
    /// FSF `extinctionValue == VALUE_DRAW` on `ALL_PIECES` (Shatar Robado).
    bare_king_draw: Option<bool>,
    /// FSF `checkCounting` where a single check already wins (Kar Ouk / Check-Shogi).
    wins_on_check: Option<bool>,
    /// The royalty model implied by `extinctionPseudoRoyal` / `dupleCheck` / a
    /// non-royal king.
    royal: Option<RoyalRule>,
}

impl Expect {
    const fn new(name: &'static str, cite: &'static str, board: (u8, u8), castling: bool) -> Self {
        Expect {
            name,
            cite,
            board,
            castling,
            promo: None,
            double_step: None,
            en_passant: None,
            stalemate_loss: None,
            bare_king_loss: None,
            bare_king_draw: None,
            wins_on_check: None,
            royal: None,
        }
    }
    const fn promo(mut self, roles: &'static [WideRole]) -> Self {
        self.promo = Some(roles);
        self
    }
    const fn dstep(mut self, ranks: &'static [u8]) -> Self {
        self.double_step = Some(ranks);
        self
    }
    const fn ep(mut self, v: bool) -> Self {
        self.en_passant = Some(v);
        self
    }
    const fn sloss(mut self, v: bool) -> Self {
        self.stalemate_loss = Some(v);
        self
    }
    const fn bk_loss(mut self, v: bool) -> Self {
        self.bare_king_loss = Some(v);
        self
    }
    const fn bk_draw(mut self, v: bool) -> Self {
        self.bare_king_draw = Some(v);
        self
    }
    const fn win_chk(mut self, v: bool) -> Self {
        self.wins_on_check = Some(v);
        self
    }
    const fn royal(mut self, v: RoyalRule) -> Self {
        self.royal = Some(v);
        self
    }
}

/// The standard promotion set `{Q, R, B, N}` (FSF default `promotionPieceTypes`).
const QRBN: &[WideRole] = &[Queen, Rook, Bishop, N];

/// The transcribed FSF expectation table. Every row cites its `variant.cpp`
/// constructor; the defaults it builds on are documented at the module level.
fn table() -> Vec<Expect> {
    use RoyalRule::{Checkmate, MultiRoyalAnySurvives, NonRoyal, PseudoRoyalAllSurvive};
    vec![
        // ---- concrete 8x8 engine (all `FairyStockfish` oracles) -----------------
        Expect::new("chess", "chess_variant", (8, 8), true)
            .promo(QRBN)
            .dstep(&[1])
            .ep(true)
            .royal(Checkmate),
        Expect::new("chess960", "chess960_variant", (8, 8), true)
            .promo(QRBN)
            .dstep(&[1])
            .ep(true),
        Expect::new("atomic", "atomic_variant", (8, 8), true)
            .promo(QRBN)
            .dstep(&[1])
            .ep(true),
        Expect::new("crazyhouse", "crazyhouse_variant", (8, 8), true)
            .promo(QRBN)
            .dstep(&[1])
            .ep(true),
        Expect::new("kingofthehill", "kingofthehill_variant", (8, 8), true)
            .promo(QRBN)
            .dstep(&[1]),
        Expect::new("3check", "threecheck_variant", (8, 8), true)
            .promo(QRBN)
            .dstep(&[1]),
        // Racing Kings: pawnless, `castling = false`, `checking = false`.
        Expect::new("racingkings", "racingkings_variant", (8, 8), false).promo(QRBN),
        // Horde: White also double-steps from the first rank (`doubleStepRegion |= Rank1BB`).
        Expect::new("horde", "horde_variant", (8, 8), true)
            .promo(QRBN)
            .dstep(&[0, 1])
            .ep(true),
        // Giveaway/Antichess: non-royal king (COMMONER), forced captures, no castling.
        Expect::new(
            "giveaway",
            "giveaway_variant / antichess_variant",
            (8, 8),
            false,
        )
        .royal(NonRoyal),
        // ---- chess-family wide variants -----------------------------------------
        Expect::new("nocastle", "nocastle_variant", (8, 8), false)
            .promo(QRBN)
            .dstep(&[1])
            .ep(true),
        // Torpedo: `doubleStepRegion = AllSquares`.
        Expect::new("torpedo", "torpedo_variant", (8, 8), true)
            .promo(QRBN)
            .dstep(&[0, 1, 2, 3, 4, 5, 6, 7])
            .ep(true),
        Expect::new("berolina", "berolina_variant", (8, 8), true)
            .promo(QRBN)
            .dstep(&[1])
            .ep(true),
        Expect::new("pawnsideways", "pawnsideways_variant", (8, 8), true)
            .promo(QRBN)
            .dstep(&[1])
            .ep(true),
        Expect::new("pawnback", "pawnback_variant", (8, 8), true)
            .promo(QRBN)
            .dstep(&[1])
            .ep(true),
        // Legan: `doubleStep = false`, no en passant. (double_step is a known divergence.)
        Expect::new("legan", "legan_variant", (8, 8), false)
            .promo(QRBN)
            .ep(false),
        Expect::new("amazon", "amazon_variant", (8, 8), true)
            .promo(&[Angel, Rook, Bishop, N])
            .dstep(&[1])
            .ep(true),
        // Georgian: `castling = false`, `enPassantRegion = 0`.
        Expect::new("georgian", "georgian_variant", (8, 8), false)
            .promo(&[Angel, Rook, Bishop, N])
            .dstep(&[1])
            .ep(false),
        Expect::new("nightrider", "nightrider_variant", (8, 8), true)
            .promo(&[Queen, Rook, Bishop, Nightrider])
            .dstep(&[1])
            .ep(true),
        // Grasshopper: `doubleStep = false`.
        Expect::new("grasshopper", "grasshopper_variant", (8, 8), true)
            .promo(&[Queen, Rook, Bishop, N, Grasshopper])
            .dstep(&[]),
        Expect::new("hoppelpoppel", "hoppelpoppel_variant", (8, 8), true)
            .promo(&[Queen, Rook, BishopKnight, KnightBishop])
            .dstep(&[1])
            .ep(true),
        Expect::new("newzealand", "newzealand_variant", (8, 8), true)
            .promo(&[Queen, Rookni, Bishop, Lancer])
            .dstep(&[1])
            .ep(true),
        Expect::new("almost", "almost_variant", (8, 8), true)
            .promo(&[Elephant, Rook, Bishop, N])
            .dstep(&[1])
            .ep(true),
        Expect::new("perfect", "perfect_variant", (8, 8), true)
            .promo(&[Angel, Elephant, Hawk, Queen, Rook, Bishop, N])
            .dstep(&[1])
            .ep(true),
        Expect::new("seirawan", "seirawan_variant", (8, 8), true)
            .promo(&[Queen, Rook, Bishop, N, Hawk, Elephant])
            .dstep(&[1])
            .ep(true),
        Expect::new("shouse", "shouse_variant", (8, 8), true)
            .promo(&[Queen, Rook, Bishop, N, Hawk, Elephant])
            .dstep(&[1])
            .ep(true),
        Expect::new("dragon", "dragon_variant", (8, 8), true)
            .promo(&[Queen, Rook, Bishop, N, Hawk])
            .dstep(&[1])
            .ep(true),
        // Extinction / royalty families.
        Expect::new("extinction", "extinction_variant", (8, 8), true)
            .dstep(&[1])
            .royal(NonRoyal),
        Expect::new("kinglet", "kinglet_variant", (8, 8), true)
            .dstep(&[1])
            .royal(NonRoyal),
        Expect::new("threekings", "threekings_variant", (8, 8), true)
            .dstep(&[1])
            .royal(NonRoyal),
        Expect::new("petrified", "petrified_variant", (8, 8), true)
            .dstep(&[1])
            .royal(PseudoRoyalAllSurvive),
        Expect::new("coregal", "coregal_variant", (8, 8), true)
            .promo(QRBN)
            .dstep(&[1])
            .royal(PseudoRoyalAllSurvive),
        Expect::new("spartan", "spartan_variant", (8, 8), true)
            .dstep(&[1])
            .royal(MultiRoyalAnySurvives),
        Expect::new("knightmate", "knightmate_variant", (8, 8), true)
            .dstep(&[1])
            .ep(true),
        Expect::new("bughouse", "bughouse_variant", (8, 8), true)
            .promo(QRBN)
            .dstep(&[1]),
        Expect::new("pocketknight", "pocketknight_variant", (8, 8), true)
            .promo(QRBN)
            .dstep(&[1])
            .ep(true),
        Expect::new("placement", "placement_variant", (8, 8), true).promo(QRBN),
        // ---- Shatranj / Makruk families (`doubleStep = false`, no double-step) ---
        // Shatranj: stalemate is a loss; bare king loses (`extinction ALL, count 1, -MATE`).
        Expect::new("shatranj", "shatranj_variant", (8, 8), false)
            .promo(&[Met])
            .dstep(&[])
            .sloss(true)
            .bk_loss(true),
        // Chaturanga: keeps Shatranj's stalemate-loss but drops the bare-king rule.
        Expect::new("chaturanga", "chaturanga_variant", (8, 8), false)
            .promo(&[Met])
            .dstep(&[])
            .sloss(true)
            .bk_loss(false),
        Expect::new("makruk", "makruk_variant", (8, 8), false)
            .promo(&[Met])
            .dstep(&[]),
        Expect::new("makpong", "makpong_variant", (8, 8), false)
            .promo(&[Met])
            .dstep(&[]),
        Expect::new("cambodian", "cambodian_variant", (8, 8), false)
            .promo(&[Met])
            .dstep(&[]),
        // Kar Ouk: `checkCounting` — the first check wins.
        Expect::new("karouk", "karouk_variant", (8, 8), false)
            .promo(&[Met])
            .dstep(&[])
            .win_chk(true),
        Expect::new("asean", "asean_variant", (8, 8), false)
            .promo(&[N, Rook, Met, Silver])
            .dstep(&[]),
        Expect::new("sittuyin", "sittuyin_variant", (8, 8), false)
            .promo(&[Met])
            .dstep(&[]),
        // Shatar: `extinctionValue = VALUE_DRAW` (Robado bare-king draw).
        Expect::new("shatar", "shatar_variant", (8, 8), false)
            .promo(&[General])
            .dstep(&[])
            .bk_draw(true),
        // ---- boards other than 8x8 ----------------------------------------------
        Expect::new("losalamos", "losalamos_variant", (6, 6), false)
            .promo(&[Queen, Rook, N])
            .dstep(&[])
            .ep(false),
        Expect::new("gardner", "gardner_variant", (5, 5), false)
            .promo(QRBN)
            .dstep(&[])
            .ep(false),
        Expect::new("minixiangqi", "minixiangqi_variant", (7, 7), false),
        // Shogi family (`minishogi_variant_base`: 5x5, `castling = false`). pawn -> Gold.
        Expect::new("minishogi", "minishogi_variant", (5, 5), false).promo(&[Gold]),
        Expect::new("judkins", "judkinsshogi_variant", (6, 6), false).promo(&[Gold]),
        Expect::new("gorogoro", "gorogoroshogi_variant", (5, 6), false).promo(&[Gold]),
        Expect::new("euroshogi", "euroshogi_variant", (8, 8), false).promo(&[Gold]),
        Expect::new("kyotoshogi", "kyotoshogi_variant", (5, 5), false),
        Expect::new("micro", "microshogi_variant", (4, 5), false),
        // Dobutsu: 3x4, non-royal king (COMMONER), flag + extinction.
        Expect::new("dobutsu", "dobutsu_variant", (3, 4), false).royal(NonRoyal),
        Expect::new("tori", "torishogi_variant", (7, 7), false),
        Expect::new("shogi", "shogi_variant", (9, 9), false).promo(&[Gold]),
        // Check-Shogi: `checkCounting` — the first check wins.
        Expect::new("checkshogi", "checkshogi_variant", (9, 9), false).win_chk(true),
        Expect::new("shoshogi", "shoshogi_variant", (9, 9), false).royal(PseudoRoyalAllSurvive),
        // Capablanca family (10x8).
        Expect::new("capablanca", "capablanca_variant", (10, 8), true)
            .promo(&[Queen, Rook, Bishop, N, Hawk, Elephant])
            .dstep(&[1])
            .ep(true),
        Expect::new("gothic", "gothic_variant", (10, 8), true)
            .promo(&[Queen, Rook, Bishop, N, Hawk, Elephant])
            .dstep(&[1]),
        Expect::new("embassy", "embassy_variant", (10, 8), true)
            .promo(&[Queen, Rook, Bishop, N, Hawk, Elephant])
            .dstep(&[1]),
        Expect::new("caparandom", "caparandom_variant", (10, 8), true)
            .promo(&[Queen, Rook, Bishop, N, Hawk, Elephant])
            .dstep(&[1]),
        Expect::new("janus", "janus_variant", (10, 8), true)
            .promo(&[Hawk, Queen, Rook, Bishop, N])
            .dstep(&[1]),
        Expect::new("centaur", "centaur_variant", (10, 8), true)
            .promo(&[Queen, Rook, Bishop, N, Kheshig])
            .dstep(&[1]),
        // 9x9 with a compound, `doubleStepRegion = Rank2BB`.
        Expect::new("modern", "modern_variant", (9, 9), true)
            .promo(&[Queen, Rook, Bishop, N, Hawk])
            .dstep(&[1]),
        Expect::new("chancellor", "chancellor_variant", (9, 9), true)
            .promo(&[Queen, Rook, Bishop, N, Elephant])
            .dstep(&[1]),
        // Courier: 12x8, stalemate-loss + bare-king-loss like Shatranj.
        Expect::new("courier", "courier_variant", (12, 8), false)
            .promo(&[Met])
            .dstep(&[])
            .sloss(true)
            .bk_loss(true),
        // 10x10, `doubleStepRegion = Rank3BB` (0-based rank 2), `castling = false`.
        Expect::new("grand", "grand_variant", (10, 10), false)
            .promo(&[Queen, Rook, Bishop, N, Hawk, Elephant])
            .dstep(&[2]),
        Expect::new("tencubed", "tencubed_variant", (10, 10), false)
            .promo(&[Queen, Elephant, Hawk])
            .dstep(&[2]),
        Expect::new("opulent", "opulent_variant", (10, 10), false).dstep(&[2]),
        Expect::new("shako", "shako_variant", (10, 10), true)
            .promo(&[Queen, Rook, Bishop, N, Cannon, FersAlfil])
            .dstep(&[2]),
        // Xiangqi family (9x10). stalemate-loss is a known divergence.
        Expect::new("xiangqi", "xiangqi_variant", (9, 10), false),
        Expect::new("manchu", "manchu_variant", (9, 10), false),
        Expect::new("janggi", "janggi_variant", (9, 10), false),
    ]
}

/// Two multisets of roles are equal (order-insensitive).
fn role_set_eq(a: &[WideRole], b: &[WideRole]) -> bool {
    let mut a = a.to_vec();
    let mut b = b.to_vec();
    a.sort_unstable();
    b.sort_unstable();
    a == b
}

/// The load-bearing test: every transcribed FSF field agrees with the derived
/// `VariantRules`. A mismatch prints the variant, its `variant.cpp` citation, the
/// field, and (mcr value vs FSF value).
#[test]
fn derived_rules_agree_with_fairy_stockfish_config() {
    for e in table() {
        let r = VariantRef::from_name(e.name)
            .unwrap_or_else(|| panic!("unknown variant {}", e.name))
            .rules();
        let ctx = format!("{} ({})", e.name, e.cite);

        assert_eq!(
            (r.board.width, r.board.height),
            e.board,
            "{ctx}: board (mcr {:?} vs FSF maxFile/maxRank {:?})",
            (r.board.width, r.board.height),
            e.board
        );
        assert_eq!(
            r.castling.enabled, e.castling,
            "{ctx}: castling (mcr {} vs FSF {})",
            r.castling.enabled, e.castling
        );
        if let Some(promo) = e.promo {
            assert!(
                role_set_eq(&r.promotion.roles, promo),
                "{ctx}: promotion set (mcr {:?} vs FSF {:?})",
                r.promotion.roles,
                promo
            );
        }
        if let Some(ranks) = e.double_step {
            assert_eq!(
                r.pawns.double_step_ranks.as_slice(),
                ranks,
                "{ctx}: double-step ranks (mcr {:?} vs FSF {:?})",
                r.pawns.double_step_ranks,
                ranks
            );
        }
        if let Some(ep) = e.en_passant {
            assert_eq!(
                r.pawns.en_passant, ep,
                "{ctx}: en passant (mcr {} vs FSF {})",
                r.pawns.en_passant, ep
            );
        }
        if let Some(sl) = e.stalemate_loss {
            assert_eq!(
                r.terminal.stalemate_is_loss, sl,
                "{ctx}: stalemate_is_loss (mcr {} vs FSF {})",
                r.terminal.stalemate_is_loss, sl
            );
        }
        if let Some(bkl) = e.bare_king_loss {
            assert_eq!(
                r.terminal.bare_king_loss, bkl,
                "{ctx}: bare_king_loss (mcr {} vs FSF {})",
                r.terminal.bare_king_loss, bkl
            );
        }
        if let Some(bkd) = e.bare_king_draw {
            assert_eq!(
                r.terminal.bare_king_draw, bkd,
                "{ctx}: bare_king_draw (mcr {} vs FSF {})",
                r.terminal.bare_king_draw, bkd
            );
        }
        if let Some(wc) = e.wins_on_check {
            assert_eq!(
                r.terminal.wins_on_check, wc,
                "{ctx}: wins_on_check (mcr {} vs FSF {})",
                r.terminal.wins_on_check, wc
            );
        }
        if let Some(royal) = e.royal {
            assert_eq!(
                r.terminal.royal, royal,
                "{ctx}: royal (mcr {:?} vs FSF {:?})",
                r.terminal.royal, royal
            );
        }
    }
}

/// The extinction / flag / check terminals that are declared with concrete
/// parameters, cross-checked against the transcribed FSF config.
#[test]
fn terminal_parameters_agree_with_fairy_stockfish_config() {
    // extinction_variant: `extinctionPieceTypes = COMMONER|Q|R|B|N|PAWN` (COMMONER =
    // the non-royal king), `extinctionValue = -VALUE_MATE`, default count 0.
    let ext = VariantRef::from_name("extinction").unwrap().rules();
    let e = ext.terminal.extinction.expect("extinction watches a set");
    assert!(
        role_set_eq(&e.watched, &[Pawn, N, Bishop, Rook, Queen, King]),
        "extinction watched (mcr {:?})",
        e.watched
    );
    assert_eq!(
        e.threshold, 0,
        "extinction threshold vs FSF extinctionPieceCount 0"
    );

    // kinglet_variant: `extinctionPieceTypes = PAWN`.
    let kl = VariantRef::from_name("kinglet").unwrap().rules();
    let e = kl.terminal.extinction.expect("kinglet watches the pawn");
    assert!(
        role_set_eq(&e.watched, &[Pawn]),
        "kinglet watched (mcr {:?})",
        e.watched
    );
    assert_eq!(e.threshold, 0);

    // threekings_variant: `extinctionPieceTypes = COMMONER`, `extinctionPieceCount = 2`.
    let tk = VariantRef::from_name("threekings").unwrap().rules();
    let e = tk.terminal.extinction.expect("threekings watches the king");
    assert!(
        role_set_eq(&e.watched, &[King]),
        "threekings watched (mcr {:?})",
        e.watched
    );
    assert_eq!(
        e.threshold, 2,
        "threekings threshold vs FSF extinctionPieceCount 2"
    );

    // petrified_variant: `extinctionPieceTypes = COMMONER` (the pseudo-royal king).
    let pf = VariantRef::from_name("petrified").unwrap().rules();
    let e = pf.terminal.extinction.expect("petrified watches the king");
    assert!(
        role_set_eq(&e.watched, &[King]),
        "petrified watched (mcr {:?})",
        e.watched
    );
    assert_eq!(e.threshold, 0);

    // dobutsu_variant: `flagPiece = COMMONER`, `flagRegion = Rank4BB` (0-based 3),
    // `flagPieceSafe = true` (the "try" must be safe).
    let db = VariantRef::from_name("dobutsu").unwrap().rules();
    let f = db.terminal.flag_win.expect("dobutsu has a flag win");
    assert_eq!(f.rank_white, 3, "dobutsu flag rank vs FSF Rank4BB");
    assert!(
        f.requires_safe,
        "dobutsu flag must be safe vs FSF flagPieceSafe"
    );

    // racingkings_variant: `flagRegion = Rank8BB` (0-based 7), no safety requirement.
    let rk = VariantRef::from_name("racingkings").unwrap().rules();
    let f = rk.terminal.flag_win.expect("racing kings has a flag win");
    assert_eq!(f.rank_white, 7, "racing kings flag rank vs FSF Rank8BB");
    assert!(!f.requires_safe);

    // kingofthehill_variant: `flagRegion = (Rank4|Rank5) & (FileD|FileE)` -> a region win.
    let koth = VariantRef::from_name("kingofthehill").unwrap().rules();
    assert!(
        koth.terminal.region_win.is_some(),
        "king of the hill has a region-goal win"
    );

    // threecheck_variant: `checkCounting` with a 3+3 counter -> win on the third check.
    let tc = VariantRef::from_name("3check").unwrap().rules();
    assert_eq!(
        tc.terminal.check_count_to_win,
        Some(3),
        "three-check count vs FSF 3+3"
    );
    assert!(tc.terminal.wins_on_check);
}

/// Divergences the cross-check found: mcr's current (differing) value is pinned so
/// the suite stays green, while a future fix that aligns mcr with FSF will trip this
/// test and prompt an update. See the module docs for the full analysis.
#[test]
fn known_divergences() {
    // (1) `stalemate_is_loss` for the shogi / xiangqi families. FSF declares
    //     `stalemateValue = -VALUE_MATE` (a loss) in `minishogi_variant_base` and
    //     `minixiangqi_variant`; mcr leaves the default draw. For xiangqi this is a
    //     genuine outcome bug (stalemate loses in real xiangqi); perft never sees it
    //     because a stalemated node has zero moves. Janggi is excluded — it can pass,
    //     so it is never stalemated.
    const STALEMATE_LOSS_MISSING: &[&str] = &[
        "shogi",
        "minishogi",
        "kyotoshogi",
        "micro",
        "gorogoro",
        "judkins",
        "euroshogi",
        "tori",
        "checkshogi",
        "shoshogi",
        "xiangqi",
        "minixiangqi",
        "manchu",
    ];
    for name in STALEMATE_LOSS_MISSING {
        let r = VariantRef::from_name(name).unwrap().rules();
        assert!(
            !r.terminal.stalemate_is_loss,
            "{name}: KNOWN DIVERGENCE RESOLVED — mcr now reports stalemate_is_loss, \
             matching FSF stalemateValue = -VALUE_MATE; move this row into the \
             agreement table."
        );
    }

    // (2) Legan's vestigial double-step. FSF `legan_variant()` sets `doubleStep = false`;
    //     mcr reports `[1]` because the Legan pawn's directional move is generated
    //     outside the generic double-push path (perft still matches FSF node-for-node).
    let legan = VariantRef::from_name("legan").unwrap().rules();
    assert_eq!(
        legan.pawns.double_step_ranks.as_slice(),
        &[1],
        "legan: KNOWN DIVERGENCE CHANGED — mcr no longer reports the vestigial \
         double-step; reconcile with FSF doubleStep = false."
    );
}
