//! Concrete fairy variants built on the generic [`WideVariant`] layer.
//!
//! Each module here is a zero-sized [`WideVariant`] rule layer plus a
//! [`GenericPosition`] type alias for it. The first is [`makruk`] (Makruk / Thai
//! chess), the opening Phase 1 fairy variant per
//! `docs/fairy-variants-architecture.md`; later variants land alongside it.
//!
//! [`WideVariant`]: super::WideVariant
//! [`GenericPosition`]: super::GenericPosition

pub mod aiwok;
pub mod alice;
pub mod almost;
pub mod amazon;
pub mod asean;
pub mod berolina;
pub mod bughouse;
pub mod cambodian;
pub mod cannonshogi;
pub mod capablanca;
pub mod capahouse;
pub mod caparandom;
pub mod centaur;
pub mod chak;
pub mod chancellor;
pub mod chaturanga;
pub mod checkshogi;
pub mod chennis;
pub mod chigorin;
pub mod chu;
pub mod codrus;
pub mod coregal;
pub mod courier;
pub mod dai;
pub mod dobutsu;
pub mod dragon;
pub mod duck;
pub mod embassy;
pub mod empire;
pub mod euroshogi;
pub mod extinction;
pub mod fogofwar;
pub mod gardner;
pub mod georgian;
pub mod giveaway;
pub mod gorogoro;
pub mod gothic;
pub mod grand;
pub mod grandhouse;
pub mod grasshopper;
pub mod hoppelpoppel;
pub mod janggi;
pub mod janus;
pub mod jieqi;
pub mod judkins;
pub mod karouk;
pub mod khans;
pub mod kinglet;
pub mod knightmate;
pub mod kyotoshogi;
pub mod legan;
pub mod losalamos;
pub mod losers;
pub mod makpong;
pub mod makruk;
pub mod manchu;
pub mod mansindam;
pub mod micro;
pub mod minishogi;
pub mod minixiangqi;
pub mod misere;
pub mod modern;
pub mod newzealand;
pub mod nightrider;
pub mod nocastle;
pub mod okisakishogi;
pub mod opulent;
pub mod orda;
pub mod ordamirror;
pub mod pawnback;
pub mod pawnsideways;
pub mod perfect;
pub mod petrified;
pub mod placement;
pub mod pocketknight;
pub mod seirawan;
pub mod shako;
pub mod shatar;
pub mod shatranj;
pub mod shinobi;
pub mod shogi;
pub mod shogun;
pub mod shoshogi;
pub mod shouse;
pub mod sittuyin;
pub mod spartan;
pub mod suicide;
pub mod synochess;
pub mod tencubed;
pub mod tenjiku;
pub mod threekings;
pub mod tori;
pub mod torpedo;
pub mod washogi;
pub mod xiangfu;
pub mod xiangqi;
pub mod yari;

pub use aiwok::{Aiwok, AiwokRules};
pub use alice::{Alice, AliceRules};
pub use almost::{Almost, AlmostRules};
pub use amazon::{Amazon, AmazonRules};
pub use asean::{Asean, AseanRules};
pub use berolina::{Berolina, BerolinaRules};
pub use bughouse::{Bughouse, BughouseRules};
pub use cambodian::{Cambodian, CambodianRules};
pub use cannonshogi::{CannonShogi, CannonShogiRules};
pub use capablanca::{Capablanca, CapablancaRules};
pub use capahouse::{Capahouse, CapahouseRules};
pub use caparandom::{Caparandom, CaparandomRules};
pub use centaur::{Centaur, CentaurRules};
pub use chak::{Chak, ChakRules};
pub use chancellor::{Chancellor, ChancellorRules};
pub use chaturanga::{Chaturanga, ChaturangaRules};
pub use checkshogi::{CheckShogi, CheckShogiRules};
pub use chennis::{Chennis, ChennisRules};
pub use chigorin::{Chigorin, ChigorinRules};
pub use chu::{Chu, ChuRules};
pub use codrus::{Codrus, CodrusRules};
pub use coregal::{Coregal, CoregalRules};
pub use courier::{Courier, CourierRules};
pub use dai::{Dai, DaiRules};
pub use dobutsu::{Dobutsu, DobutsuRules};
pub use dragon::{Dragon, DragonRules};
pub use duck::{Duck, DuckRules};
pub use embassy::{Embassy, EmbassyRules};
pub use empire::{Empire, EmpireRules};
pub use euroshogi::{EuroShogi, EuroShogiRules};
pub use extinction::{Extinction, ExtinctionRules};
pub use fogofwar::{FogOfWar, FogOfWarRules};
pub use gardner::{Gardner, GardnerRules};
pub use georgian::{Georgian, GeorgianRules};
pub use giveaway::{Giveaway, GiveawayRules};
pub use gorogoro::{Gorogoro, GorogoroRules};
pub use gothic::{Gothic, GothicRules};
pub use grand::{Grand, GrandRules};
pub use grandhouse::{Grandhouse, GrandhouseRules};
pub use grasshopper::{Grasshopper, GrasshopperRules};
pub use hoppelpoppel::{HoppelPoppel, HoppelPoppelRules};
pub use janggi::{Janggi, JanggiRules};
pub use janus::{Janus, JanusRules};
pub use jieqi::{Jieqi, JieqiRules};
pub use judkins::{Judkins, JudkinsRules};
pub use karouk::{Karouk, KaroukRules};
pub use khans::{Khans, KhansRules};
pub use kinglet::{Kinglet, KingletRules};
pub use knightmate::{Knightmate, KnightmateRules};
pub use kyotoshogi::{Kyotoshogi, KyotoshogiRules};
pub use legan::{Legan, LeganRules};
pub use losalamos::{Losalamos, LosalamosRules};
pub use losers::{Losers, LosersRules};
pub use makpong::{Makpong, MakpongRules};
pub use makruk::{Makruk, MakrukRules};
pub use manchu::{Manchu, ManchuRules};
pub use mansindam::{Mansindam, MansindamRules};
pub use micro::{Micro, MicroRules};
pub use minishogi::{Minishogi, MinishogiRules};
pub use minixiangqi::{Minixiangqi, MinixiangqiRules};
pub use misere::{Misere, MisereRules};
pub use modern::{Modern, ModernRules};
pub use newzealand::{Newzealand, NewzealandRules};
pub use nightrider::{Nightrider, NightriderRules};
pub use nocastle::{Nocastle, NocastleRules};
pub use okisakishogi::{OkisakiShogi, OkisakiShogiRules};
pub use opulent::{Opulent, OpulentRules};
pub use orda::{Orda, OrdaRules};
pub use ordamirror::{Ordamirror, OrdamirrorRules};
pub use pawnback::{Pawnback, PawnbackRules};
pub use pawnsideways::{Pawnsideways, PawnsidewaysRules};
pub use perfect::{Perfect, PerfectRules};
pub use petrified::{Petrified, PetrifiedRules};
pub use placement::{Placement, PlacementRules};
pub use pocketknight::{Pocketknight, PocketknightRules};
pub use seirawan::{Seirawan, SeirawanRules};
pub use shako::{Shako, ShakoRules};
pub use shatar::{Shatar, ShatarRules};
pub use shatranj::{Shatranj, ShatranjRules};
pub use shinobi::{Shinobi, ShinobiRules};
pub use shogi::{Shogi, ShogiRules};
pub use shogun::{Shogun, ShogunRules};
pub use shoshogi::{ShoShogi, ShoShogiRules};
pub use shouse::{Shouse, ShouseRules};
pub use sittuyin::{Sittuyin, SittuyinRules};
pub use spartan::{Spartan, SpartanRules};
pub use suicide::{Suicide, SuicideRules};
pub use synochess::{Synochess, SynochessRules};
pub use tencubed::{Tencubed, TencubedRules};
pub use tenjiku::{Tenjiku, TenjikuRules};
pub use threekings::{Threekings, ThreekingsRules};
pub use tori::{Tori, ToriRules};
pub use torpedo::{Torpedo, TorpedoRules};
pub use washogi::{Washogi, WashogiRules};
pub use xiangfu::{Xiangfu, XiangfuRules};
pub use xiangqi::{Xiangqi, XiangqiRules};
pub use yari::{Yari, YariRules};
