//! Three kings chess (8x8) on the generic engine — **standard chess movement in
//! which each side starts with three non-royal kings and loses the moment one of
//! them is captured**. Validated against Fairy-Stockfish `UCI_Variant threekings`
//! (a built-in; `threekings_variant()`).
//!
//! Three kings chess keeps every standard chess move — the same sliders and
//! leapers, castling, en passant, and standard `Q`/`R`/`B`/`N` promotion — but
//! **there is no check and no checkmate**: each king is a non-royal **Commoner**
//! (it still steps one square in any direction, but it is an ordinary, capturable
//! piece). Each side fields **three** of them, and a side loses **by extinction**
//! the instant its king count drops to two:
//!
//! * the game ends the moment a side is reduced to **two** kings — i.e. losing
//!   **any one** of its three kings is a loss;
//! * capturing an enemy king is legal (it is the decisive move);
//! * only the king (Commoner) is watched — losing every queen, knight, bishop, or
//!   pawn is fine; and
//! * a side may move into "check" and may leave a king attacked (there is no
//!   royal to keep safe).
//!
//! ## The shared extinction terminal
//!
//! The loss condition is the **generic** [`WideVariant::extinction_rule`] hook: an
//! [`ExtinctionRule`] naming the *watched* piece types and the *threshold* at or
//! below which any of them counts as extinct. Three kings watches only the king
//! (`[King]`) with `threshold = 2`, so a side loses when its king count reaches
//! two. Extinction chess is the sibling variant that watches the whole army with
//! `threshold = 0`; the same hook expresses both.
//!
//! ## King handling — a non-royal Commoner
//!
//! The non-royal king reuses the exact machinery Extinction / Fog of War / Duck
//! introduced: an empty [`royal_squares`](WideVariant::royal_squares) set makes the
//! generic king-safety code report "never in check", and
//! [`non_royal_king`](WideVariant::non_royal_king) routes the standard generator
//! through its non-royal branch (every pseudo-legal board move is legal, no check
//! mask / pin / king-danger filter). The three kings are generated by the same
//! multi-king movegen Extinction chess uses for a promoted second Commoner —
//! here it is exercised from move 1. Castling stays enabled (the FEN grants no
//! castling rights anyway, there being no rooks in the start array) and is never
//! restricted by attacked squares. Because there is no check, the extinction rule
//! is the game's only decisive terminal.
//!
//! ## Confirmed starting FEN
//!
//! Pinned against Fairy-Stockfish's `UCI_Variant threekings`:
//!
//! ```text
//! knbqkbnk/pppppppp/8/8/8/8/PPPPPPPP/KNBQKBNK w - - 0 1
//! ```
//!
//! Each side has kings (Commoners spelled `k`/`K`) on files a, e, and h, a queen,
//! two bishops, two knights, and eight pawns — **no rooks**, and no castling
//! rights.
//!
//! [`ExtinctionRule`]: crate::geometry::ExtinctionRule

use crate::geometry::position::{
    GenericCastling, GenericGating, GenericPlacement, GenericPosition, GenericState,
};
use crate::geometry::{Bitboard, Board, Chess8x8, ExtinctionRule, WideRole, WideVariant};
use crate::Color;

/// The 8x8 starting placement: three kings per side on files a/e/h, no rooks.
const THREEKINGS_START_PLACEMENT: &str = "knbqkbnk/pppppppp/8/8/8/8/PPPPPPPP/KNBQKBNK";

/// The single watched type: the non-royal king ([`WideRole::King`]). A side loses
/// the instant its king count drops to `threshold` (2) or fewer.
const THREEKINGS_WATCHED: &[WideRole] = &[WideRole::King];

/// The Three kings chess rule layer: a zero-sized [`WideVariant`] over [`Chess8x8`].
///
/// It overrides only what Three kings changes about standard chess: the king is a
/// non-royal Commoner (via [`WideVariant::royal_squares`] and
/// [`WideVariant::non_royal_king`], like Extinction), and the game ends by
/// extinction of the king type at a threshold of two (via
/// [`WideVariant::extinction_rule`]). Every piece's movement, castling, en passant,
/// and standard `Q`/`R`/`B`/`N` promotion is the standard trait default.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Default)]
pub struct ThreekingsRules;

impl WideVariant<Chess8x8> for ThreekingsRules {
    /// The tightest prefix of `WideRole::ALL` that still contains every role this
    /// variant can field (Pawn..King, the standard army; promotions are Queen /
    /// Rook / Bishop / Knight, all within the prefix). See [`WideVariant::ROLE_SPAN`].
    const ROLE_SPAN: usize = 6;

    fn starting_position() -> (Board<Chess8x8>, GenericState<Chess8x8>) {
        let board = Board::<Chess8x8>::from_fen_placement(THREEKINGS_START_PLACEMENT)
            .expect("the Three kings starting placement is valid on an 8x8 board");
        let state = GenericState {
            turn: Color::White,
            // No castling rights: the start array has no rooks (files k/n/b/q/k/b/n/k).
            castling: GenericCastling::NONE,
            ep_square: None,
            ep_captured: None,
            gating: GenericGating::NONE,
            duck: None,
            placement: GenericPlacement::NONE,
            halfmove_clock: 0,
            fullmove_number: 1,
            consecutive_passes: 0,
            board_b: Bitboard::EMPTY,
            petrified: Bitboard::EMPTY,
        };
        (board, state)
    }

    // --- non-royal Commoner kings (no check) ------------------------------

    fn non_royal_king() -> bool {
        // Each king is a non-royal Commoner: the standard generator's non-royal
        // branch emits every pseudo-legal board move (no check mask, no pins, no
        // king-danger filter), so a king may step onto an attacked square, a piece
        // may move while "pinned", and capturing an enemy king is a legal move. The
        // multi-king loop generates all three kings' moves.
        true
    }

    fn royal_squares<const R: usize>(
        _board: &Board<Chess8x8, R>,
        _color: Color,
    ) -> Bitboard<Chess8x8> {
        // The kings are **not royal**: an empty royal set makes the generic
        // king-safety machinery report "never in check". A side loses not by
        // checkmate but by extinction (below), when it is reduced to two kings.
        Bitboard::EMPTY
    }

    // --- extinction terminal (the king type, threshold 2) -----------------

    /// A side loses the moment its king count drops to two. Three kings watches only
    /// the king (`[King]`) with `threshold = 2` (FSF `extinctionPieceTypes =
    /// {COMMONER}`, `extinctionPieceCount = 2`), so losing any one of the three
    /// kings — the count falling from three through two — is the decisive terminal.
    fn extinction_rule() -> Option<ExtinctionRule> {
        Some(ExtinctionRule {
            watched: THREEKINGS_WATCHED,
            threshold: 2,
            count_total: false,
            extinct_wins: false,
            opponent_min: 0,
        })
    }

    // Promotion is the standard `[Knight, Bishop, Rook, Queen]` trait default: a
    // pawn cannot promote to a king, so the king count only ever decreases.
}

/// Three kings chess as a [`GenericPosition`] over the 8x8 [`Chess8x8`] geometry.
///
/// Construct the starting position with
/// [`Threekings::startpos`](GenericPosition::startpos) or parse a plain-chess FEN
/// with [`Threekings::from_fen`](GenericPosition::from_fen). Movement is the
/// no-check standard-chess set; the game ends when a side is reduced to two kings.
pub type Threekings = GenericPosition<
    Chess8x8,
    ThreekingsRules,
    { <ThreekingsRules as WideVariant<Chess8x8>>::ROLE_SPAN },
>;

#[cfg(test)]
mod tests {
    use super::*;
    use crate::geometry::{Chess8x8, WideOutcome};

    /// The canonical start FEN round-trips, has no castling rights, and the startpos
    /// is not terminal — each side has all three kings.
    #[test]
    fn startpos_fen_round_trips() {
        let pos = Threekings::startpos();
        assert_eq!(
            pos.to_fen(),
            "knbqkbnk/pppppppp/8/8/8/8/PPPPPPPP/KNBQKBNK w - - 0 1"
        );
        assert_eq!(pos.turn(), Color::White);
        assert_eq!(
            pos.board().pieces(Color::White, WideRole::King).count(),
            3,
            "white starts with three kings",
        );
        assert_eq!(pos.end_reason(), None, "the startpos is not terminal");
        assert_eq!(pos.outcome(), None);
    }

    /// The king is non-royal: a side may leave a king attacked — there is no
    /// self-check filter. All three kings are present, so nobody is extinct.
    #[test]
    fn kings_are_non_royal_no_check() {
        let pos = Threekings::startpos();
        assert!(!pos.is_check(), "a non-royal king is never in check");
        assert_eq!(pos.end_reason(), None);
    }

    /// **Adjudication test (coverage-gate registered):** a side reduced to two kings
    /// has lost by extinction. White captures one of Black's three kings; the
    /// resulting position has two Black kings (<= threshold 2), so it is terminal — a
    /// decisive win for White — and generates no moves.
    #[test]
    fn threekings_losing_a_king_loses() {
        // Both sides hold all three kings (nobody is pre-extinct): a white queen on
        // a2 faces the lone black king on a8 down the open a-file.
        let pos = Threekings::from_fen("k3kb1k/8/8/8/8/8/Q7/K3KB1K w - - 0 1").expect("valid FEN");
        assert_eq!(
            pos.board().pieces(Color::Black, WideRole::King).count(),
            3,
            "Black has three kings before the capture",
        );
        assert_eq!(pos.end_reason(), None, "not yet terminal");

        // Qxa8 removes one of Black's three kings.
        let qxa8 = pos
            .legal_moves()
            .into_iter()
            .find(|m| {
                m.from::<Chess8x8>() == crate::geometry::Square::<Chess8x8>::new(8) // a2
                    && m.to::<Chess8x8>() == crate::geometry::Square::<Chess8x8>::new(56)
                // a8
            })
            .expect("Qxa8 is a legal move");
        let after = pos.play(&qxa8);

        assert_eq!(
            after.board().pieces(Color::Black, WideRole::King).count(),
            2,
            "Black is reduced to two kings",
        );
        assert_eq!(after.extinction_loser(), Some(Color::Black));
        assert_eq!(
            after.end_reason(),
            Some(crate::geometry::WideEndReason::VariantWin)
        );
        assert_eq!(
            after.outcome(),
            Some(WideOutcome::Decisive {
                winner: Color::White
            }),
        );
        // Terminal: the losing (extinct) side generates no continuation.
        assert!(
            after.legal_moves().is_empty(),
            "an extinct position is a terminal perft leaf",
        );
    }

    /// A position where a side is *already* reduced to two kings is terminal at any
    /// depth — the same truncation Fairy-Stockfish's `go perft` reports as 0.
    #[test]
    fn two_kings_is_terminal() {
        // Black has only two kings (a queen captured one); it has already lost.
        let pos = Threekings::from_fen("k3kbn1/pppppppp/8/8/8/8/PPPPPPPP/KNBQKBNK w - - 0 1")
            .expect("valid FEN");
        assert_eq!(pos.extinction_loser(), Some(Color::Black));
        assert!(pos.legal_moves().is_empty(), "terminal — no moves");
        assert_eq!(
            pos.outcome(),
            Some(WideOutcome::Decisive {
                winner: Color::White
            }),
        );
    }
}
