/*
 * mce.h — C ABI for the mce chess engine.
 *
 * GENERATED by cbindgen from bindings/c/src/lib.rs. Do not edit by hand;
 * regenerate with:
 *     cbindgen --config cbindgen.toml --crate mce-c --output include/mce.h
 *
 * See the crate docs (and the doc comments below) for ownership, the two-call
 * buffer contract, and panic safety.
 */

#ifndef MCE_H
#define MCE_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Game-outcome codes returned by [`mce_position_outcome`].
 *
 * Kept as plain `int` values so the header exposes a stable C enum.
 */
enum MceOutcome
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : int32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    /**
     * The game is still in progress (no result yet).
     */
    MCE_OUTCOME_ONGOING = 0,
    /**
     * The game ended in a draw (stalemate, insufficient material, repetition,
     * the 75-move rule, or a variant-specific draw).
     */
    MCE_OUTCOME_DRAW = 1,
    /**
     * White has won.
     */
    MCE_OUTCOME_WHITE_WINS = 2,
    /**
     * Black has won.
     */
    MCE_OUTCOME_BLACK_WINS = 3,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum MceOutcome MceOutcome;
#else
typedef int32_t MceOutcome;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/**
 * Opaque handle to a chess position of a runtime-chosen variant.
 *
 * C code only ever holds a `McePosition*`; the layout is private. Create one
 * with [`mce_position_startpos`] / [`mce_position_new_from_fen`] and release it
 * with [`mce_position_free`].
 */
typedef struct McePosition McePosition;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Creates a position from a six-field FEN under the named `variant`.
 *
 * `variant` accepts the canonical names and aliases of [`VariantId::from_str`]
 * (e.g. `"chess"`, `"atomic"`, `"crazyhouse"`, `"koth"`, `"960"`).
 *
 * Returns a fresh owned `McePosition*`, or **NULL** if either string is NULL /
 * not valid UTF-8, the variant name is unknown, or the FEN does not parse.
 *
 * The returned pointer must be released with [`mce_position_free`].
 */
McePosition *mce_position_new_from_fen(const char *fen, const char *variant);

/**
 * Creates the starting position of the named `variant`.
 *
 * `variant` accepts the same names as [`mce_position_new_from_fen`]. Returns a
 * fresh owned `McePosition*`, or **NULL** if `variant` is NULL / not valid
 * UTF-8 / an unknown variant. Release it with [`mce_position_free`].
 */
McePosition *mce_position_startpos(const char *variant);

/**
 * Releases a position created by this library.
 *
 * `mce_position_free(NULL)` is a no-op. Calling it twice on the same non-NULL
 * pointer, or on a pointer this library did not produce, is undefined behavior.
 */
void mce_position_free(McePosition *pos);

/**
 * Writes the position's FEN into `buf` and returns the length needed
 * (including the NUL terminator). See the crate-level buffer contract. Returns
 * `0` if `pos` is NULL.
 */
uintptr_t mce_position_to_fen(const McePosition *pos, char *buf, uintptr_t buflen);

/**
 * Writes the legal moves of the side to move into `buf` as a single
 * **space-separated** list of UCI strings (e.g. `"e2e4 e2e3 g1f3 ..."`), and
 * returns the length needed including the NUL terminator. See the crate-level
 * buffer contract. An empty move list yields the empty string (`needed == 1`,
 * just the NUL). Returns `0` if `pos` is NULL.
 */
uintptr_t mce_position_legal_moves(const McePosition *pos, char *buf, uintptr_t buflen);

/**
 * Parses `uci` against the position and, if it names a legal move, plays it,
 * **mutating the handle in place** (advancing it one ply).
 *
 * Returns `0` on success. Returns a nonzero error code otherwise:
 * `1` if `pos` or `uci` is NULL or `uci` is not valid UTF-8, `2` if the move is
 * malformed or illegal in this position. On any nonzero return the position is
 * left unchanged.
 */
int mce_position_play_uci(McePosition *pos, const char *uci);

/**
 * Returns `1` if the side to move is in check, `0` if not. Returns `0` if `pos`
 * is NULL or the underlying call panics.
 */
int mce_position_is_check(const McePosition *pos);

/**
 * Returns the game outcome as an [`MceOutcome`] code (an `int`).
 *
 * `MCE_OUTCOME_ONGOING` (0) means the game is not over. Otherwise the value is
 * `DRAW`, `WHITE_WINS`, or `BLACK_WINS`. Returns `ONGOING` if `pos` is NULL or
 * the call panics (treat a NULL handle as a programming error on the caller's
 * side; this never crashes).
 */
MceOutcome mce_position_outcome(const McePosition *pos);

/**
 * Counts the leaf nodes reachable in exactly `depth` plies from this position
 * (a standard perft). Returns `0` if `pos` is NULL or the computation panics.
 *
 * Note that `depth == 0` legitimately returns `1`.
 */
uint64_t mce_perft(const McePosition *pos, uint32_t depth);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* MCE_H */
