/*
 * mcr.h — C ABI for the mcr chess rules library.
 *
 * GENERATED by cbindgen from bindings/c/src/lib.rs. Do not edit by hand;
 * regenerate with:
 *     cbindgen --config cbindgen.toml --crate mcr-c --output include/mcr.h
 *
 * See the crate docs (and the doc comments below) for ownership, the two-call
 * buffer contract, and panic safety.
 */

#ifndef MCR_H
#define MCR_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Game-outcome codes returned by [`mcr_position_outcome`].
 *
 * Kept as plain `int` values so the header exposes a stable C enum.
 */
enum McrOutcome
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : int32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    /**
     * The game is still in progress (no result yet).
     */
    MCR_OUTCOME_ONGOING = 0,
    /**
     * The game ended in a draw (stalemate, insufficient material, repetition,
     * the 75-move rule, or a variant-specific draw).
     */
    MCR_OUTCOME_DRAW = 1,
    /**
     * White has won.
     */
    MCR_OUTCOME_WHITE_WINS = 2,
    /**
     * Black has won.
     */
    MCR_OUTCOME_BLACK_WINS = 3,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum McrOutcome McrOutcome;
#else
typedef int32_t McrOutcome;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/**
 * Consolidated game-status codes returned by [`mcr_position_status`] /
 * [`mcr_fairy_position_status`].
 *
 * This mirrors the engine's `GameStatus` (issue #372): it folds *why* a game
 * ended together with the shape of the ending into one label, so a caller can
 * distinguish a checkmate from a stalemate from a variant-specific win/draw
 * without a second query. The winning side (for a decisive status) is read
 * from [`mcr_position_outcome`].
 */
enum McrStatus
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : int32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    /**
     * The game is still in progress (no terminal rule applies).
     */
    MCR_STATUS_ONGOING = 0,
    /**
     * The side to move is checkmated (in check with no legal move).
     */
    MCR_STATUS_CHECKMATE = 1,
    /**
     * The side to move has no legal move and is not in check, scored as a draw.
     */
    MCR_STATUS_STALEMATE = 2,
    /**
     * A variant-specific decisive ending (a flag / temple / baring win, a
     * perpetual-check or -chase loss, or a stalemate scored as a loss).
     */
    MCR_STATUS_VARIANT_WIN = 3,
    /**
     * A drawing rule other than stalemate (insufficient material, repetition,
     * sennichite, bikjang, counting, the move-count rule, a variant draw).
     */
    MCR_STATUS_DRAW = 4,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum McrStatus McrStatus;
#else
typedef int32_t McrStatus;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/**
 * Opaque handle to a fairy-variant chess position chosen at runtime.
 *
 * C code only ever holds a `McrFairyPosition*`; the layout is private. Create
 * one with [`mcr_fairy_position_startpos`] /
 * [`mcr_fairy_position_new_from_fen`] and release it with
 * [`mcr_fairy_position_free`].
 */
typedef struct McrFairyPosition McrFairyPosition;

/**
 * Opaque handle to a chess position of a runtime-chosen variant.
 *
 * C code only ever holds a `McrPosition*`; the layout is private. Create one
 * with [`mcr_position_startpos`] / [`mcr_position_new_from_fen`] and release it
 * with [`mcr_position_free`].
 */
typedef struct McrPosition McrPosition;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Creates a position from a six-field FEN under the named `variant`.
 *
 * `variant` accepts the canonical names and aliases of [`VariantId::from_str`]
 * (e.g. `"chess"`, `"atomic"`, `"crazyhouse"`, `"koth"`, `"960"`).
 *
 * Returns a fresh owned `McrPosition*`, or **NULL** if either string is NULL /
 * not valid UTF-8, the variant name is unknown, or the FEN does not parse.
 *
 * The returned pointer must be released with [`mcr_position_free`].
 */
McrPosition *mcr_position_new_from_fen(const char *fen, const char *variant);

/**
 * Creates the starting position of the named `variant`.
 *
 * `variant` accepts the same names as [`mcr_position_new_from_fen`]. Returns a
 * fresh owned `McrPosition*`, or **NULL** if `variant` is NULL / not valid
 * UTF-8 / an unknown variant. Release it with [`mcr_position_free`].
 */
McrPosition *mcr_position_startpos(const char *variant);

/**
 * Releases a position created by this library.
 *
 * `mcr_position_free(NULL)` is a no-op. Calling it twice on the same non-NULL
 * pointer, or on a pointer this library did not produce, is undefined behavior.
 */
void mcr_position_free(McrPosition *pos);

/**
 * Writes the position's FEN into `buf` and returns the length needed
 * (including the NUL terminator). See the crate-level buffer contract. Returns
 * `0` if `pos` is NULL.
 */
uintptr_t mcr_position_to_fen(const McrPosition *pos, char *buf, uintptr_t buflen);

/**
 * Writes the legal moves of the side to move into `buf` as a single
 * **space-separated** list of UCI strings (e.g. `"e2e4 e2e3 g1f3 ..."`), and
 * returns the length needed including the NUL terminator. See the crate-level
 * buffer contract. An empty move list yields the empty string (`needed == 1`,
 * just the NUL). Returns `0` if `pos` is NULL.
 */
uintptr_t mcr_position_legal_moves(const McrPosition *pos, char *buf, uintptr_t buflen);

/**
 * Parses `uci` against the position and, if it names a legal move, plays it,
 * **mutating the handle in place** (advancing it one ply).
 *
 * Returns `0` on success. Returns a nonzero error code otherwise:
 * `1` if `pos` or `uci` is NULL or `uci` is not valid UTF-8, `2` if the move is
 * malformed or illegal in this position. On any nonzero return the position is
 * left unchanged.
 */
int mcr_position_play_uci(McrPosition *pos, const char *uci);

/**
 * Returns `1` if the side to move is in check, `0` if not. Returns `0` if `pos`
 * is NULL or the underlying call panics.
 */
int mcr_position_is_check(const McrPosition *pos);

/**
 * Returns the game outcome as an [`McrOutcome`] code (an `int`).
 *
 * `MCR_OUTCOME_ONGOING` (0) means the game is not over. Otherwise the value is
 * `DRAW`, `WHITE_WINS`, or `BLACK_WINS`. Returns `ONGOING` if `pos` is NULL or
 * the call panics (treat a NULL handle as a programming error on the caller's
 * side; this never crashes).
 */
McrOutcome mcr_position_outcome(const McrPosition *pos);

/**
 * Counts the leaf nodes reachable in exactly `depth` plies from this position
 * (a standard perft). Returns `0` if `pos` is NULL or the computation panics.
 *
 * Note that `depth == 0` legitimately returns `1`.
 */
uint64_t mcr_perft(const McrPosition *pos, uint32_t depth);

/**
 * Returns the consolidated game status as an [`McrStatus`] code (an `int`),
 * distinguishing checkmate / stalemate / a variant-specific win / a draw. See
 * [`McrStatus`]. Returns `ONGOING` if `pos` is NULL or the call panics.
 */
McrStatus mcr_position_status(const McrPosition *pos);

/**
 * Returns `1` if `square` is attacked by any piece of `side`, `0` if not, and
 * `-1` if `pos` is NULL, either string is NULL / not valid UTF-8, `square` is
 * not a valid algebraic square, or `side` is not `"white"`/`"black"`.
 */
int mcr_position_is_attacked(const McrPosition *pos, const char *square, const char *side);

/**
 * Writes the squares of `side` pieces that attack `square` into `buf` as a
 * single **space-separated** algebraic list (e.g. `"d1 f1"`), and returns the
 * length needed including the NUL terminator (two-call buffer contract). An
 * empty set yields the empty string (`needed == 1`). Returns `0` on error
 * (NULL handle/string, bad UTF-8, bad square, or bad colour).
 */
uintptr_t mcr_position_attackers(const McrPosition *pos,
                                 const char *square,
                                 const char *side,
                                 char *buf,
                                 uintptr_t buflen);

/**
 * Writes the squares attacked (threatened) by the piece standing on `square`
 * into `buf` as a space-separated algebraic list, and returns the length needed
 * including the NUL terminator (two-call buffer contract). An empty square
 * yields the empty string (`needed == 1`). Returns `0` on error (NULL
 * handle/string, bad UTF-8, or a bad square).
 */
uintptr_t mcr_position_attacks_from(const McrPosition *pos,
                                    const char *square,
                                    char *buf,
                                    uintptr_t buflen);

/**
 * Returns the mobility of the piece on `square`: the number of squares it
 * attacks (`0` for an empty square). Returns `-1` if `pos` or `square` is NULL
 * / not valid UTF-8, or `square` is not a valid algebraic square.
 */
int mcr_position_mobility(const McrPosition *pos, const char *square);

/**
 * Creates a fairy position from a FEN under the named `variant`.
 *
 * `variant` accepts the canonical names and aliases of
 * [`WideVariantId::from_str`] (e.g. `"xiangqi"`, `"shogi"`, `"janggi"`,
 * `"orda"`, `"cchess"`).
 *
 * Returns a fresh owned `McrFairyPosition*`, or **NULL** if either string is
 * NULL / not valid UTF-8, the variant name is unknown, or the FEN does not
 * parse. Release it with [`mcr_fairy_position_free`].
 */
McrFairyPosition *mcr_fairy_position_new_from_fen(const char *fen, const char *variant);

/**
 * Creates the starting position of the named fairy `variant`.
 *
 * `variant` accepts the same names as [`mcr_fairy_position_new_from_fen`].
 * Returns a fresh owned `McrFairyPosition*`, or **NULL** if `variant` is NULL /
 * not valid UTF-8 / an unknown variant. Release it with
 * [`mcr_fairy_position_free`].
 */
McrFairyPosition *mcr_fairy_position_startpos(const char *variant);

/**
 * Releases a fairy position created by this library.
 *
 * `mcr_fairy_position_free(NULL)` is a no-op. Calling it twice on the same
 * non-NULL pointer, or on a pointer this library did not produce, is undefined
 * behavior.
 */
void mcr_fairy_position_free(McrFairyPosition *pos);

/**
 * Writes the position's FEN into `buf` and returns the length needed (including
 * the NUL terminator). See the crate-level buffer contract. Returns `0` if
 * `pos` is NULL.
 */
uintptr_t mcr_fairy_position_to_fen(const McrFairyPosition *pos, char *buf, uintptr_t buflen);

/**
 * Writes the legal moves of the side to move into `buf` as a single
 * **space-separated** list of UCI strings, and returns the length needed
 * including the NUL terminator. See the crate-level buffer contract. An empty
 * move list yields the empty string (`needed == 1`). Returns `0` if `pos` is
 * NULL.
 */
uintptr_t mcr_fairy_position_legal_moves(const McrFairyPosition *pos, char *buf, uintptr_t buflen);

/**
 * Parses `uci` against the position and, if it names a legal move, plays it,
 * **mutating the handle in place** (advancing it one ply).
 *
 * Returns `0` on success, `1` if `pos` or `uci` is NULL or `uci` is not valid
 * UTF-8, `2` if the move is malformed or illegal. On any nonzero return the
 * position is left unchanged.
 */
int mcr_fairy_position_play_uci(McrFairyPosition *pos, const char *uci);

/**
 * Returns `1` if the side to move is in check, `0` if not. Returns `0` if `pos`
 * is NULL or the underlying call panics.
 */
int mcr_fairy_position_is_check(const McrFairyPosition *pos);

/**
 * Returns the fairy game outcome as an [`McrOutcome`] code (an `int`), with the
 * same encoding as [`mcr_position_outcome`]. Returns `ONGOING` if `pos` is NULL
 * or the call panics.
 */
McrOutcome mcr_fairy_position_outcome(const McrFairyPosition *pos);

/**
 * Counts the leaf nodes reachable in exactly `depth` plies from this fairy
 * position (a perft). Returns `0` if `pos` is NULL or the computation panics.
 * `depth == 0` legitimately returns `1`.
 */
uint64_t mcr_fairy_perft(const McrFairyPosition *pos, uint32_t depth);

/**
 * Returns the consolidated fairy game status as an [`McrStatus`] code, with the
 * same encoding as [`mcr_position_status`]. Returns `ONGOING` if `pos` is NULL
 * or the call panics.
 */
McrStatus mcr_fairy_position_status(const McrFairyPosition *pos);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* MCR_H */
